#!/usr/bin/env python3
"""Export enforced rules from the Personal OS wiki into Cursor rule files.

Source of truth: os/wiki/rules/*.md (excluding README.md). Each rules page is
exported to .cursor/rules/<slug>.mdc so agents follow it. Exports are:

  - Auto-Attached when the page declares `globs:` — the rule body enters context
    only when a matching file is in play (zero cost otherwise).
  - Agent-Requested otherwise — only the one-line `description` is surfaced; the
    agent pulls the body on demand. No export uses `alwaysApply: true`, so idle
    context cost is at most one description line per rule.

Run without arguments to (re)generate exports. Run with --check to verify the
committed exports match the wiki pages (used by scripts/check-repo.sh); it exits
non-zero on any drift, missing export, or stale export.
"""

from __future__ import annotations

import argparse
import posixpath
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RULES_DIR = ROOT / "os" / "wiki" / "rules"
OUTPUT_DIR = ROOT / ".cursor" / "rules"
WIKI_BASE = "os/wiki/rules"

MARKER = "GENERATED by scripts/sync-rules.py from {source} — DO NOT EDIT (edit the wiki page and re-run)."

LINK_RE = re.compile(r"\]\(([^)]+)\)")


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def split_frontmatter(text: str) -> tuple[str, str]:
    """Return (frontmatter_body, rest) or ("", text) when no frontmatter."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return "", text
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            fm = "\n".join(lines[1:i])
            rest = "\n".join(lines[i + 1 :])
            return fm, rest
    return "", text


def parse_frontmatter(fm: str) -> dict[str, str]:
    fields: dict[str, str] = {}
    for line in fm.splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        fields[key.strip()] = value.strip()
    return fields


def parse_list(value: str) -> list[str]:
    value = value.strip()
    if value.startswith("[") and value.endswith("]"):
        value = value[1:-1]
    parts = [p.strip().strip('"').strip("'") for p in value.split(",")]
    return [p for p in parts if p]


def rewrite_links(body: str) -> str:
    """Rewrite wiki-relative markdown links to repo-root-relative paths."""

    def repl(match: re.Match[str]) -> str:
        target = match.group(1)
        if target.startswith(("http://", "https://", "#", "/")):
            return match.group(0)
        anchor = ""
        if "#" in target:
            target, _, anchor = target.partition("#")
            anchor = "#" + anchor
        resolved = posixpath.normpath(posixpath.join(WIKI_BASE, target))
        return f"]({resolved}{anchor})"

    return LINK_RE.sub(repl, body)


def strip_trailing_section(body: str, heading: str) -> str:
    """Drop a trailing '## <heading>' section (wiki-only bookkeeping)."""
    lines = body.splitlines()
    out: list[str] = []
    skipping = False
    for line in lines:
        if line.strip().lower() == f"## {heading}".lower():
            skipping = True
            continue
        if skipping and line.startswith("## "):
            skipping = False
        if not skipping:
            out.append(line)
    return "\n".join(out)


def render_export(source_rel: str, fields: dict[str, str], body: str) -> str:
    description = fields.get("description", "").strip()
    if not description:
        raise SystemExit(
            f"Rules page missing required 'description' frontmatter: {source_rel}"
        )

    globs = parse_list(fields.get("globs", "")) if fields.get("globs") else []

    body = strip_trailing_section(body, "Exports")
    body = rewrite_links(body).strip()

    fm_lines = [f"description: {description}"]
    if globs:
        fm_lines.append("globs: " + ",".join(globs))
    fm_lines.append("alwaysApply: false")

    marker = MARKER.format(source=source_rel)
    return "---\n" + "\n".join(fm_lines) + "\n---\n\n" + f"<!-- {marker} -->\n\n" + body + "\n"


def source_pages() -> list[Path]:
    return sorted(p for p in RULES_DIR.glob("*.md") if p.name != "README.md")


def target_for(page: Path) -> Path:
    return OUTPUT_DIR / f"{page.stem}.mdc"


def build_export(page: Path) -> str:
    text = read_text(page)
    fm, body = split_frontmatter(text)
    fields = parse_frontmatter(fm)
    source_rel = f"{WIKI_BASE}/{page.name}"
    return render_export(source_rel, fields, body)


def is_generated(path: Path) -> bool:
    if not path.exists():
        return False
    return "GENERATED by scripts/sync-rules.py" in read_text(path)


def run(check: bool) -> int:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    problems: list[str] = []
    expected_targets: set[Path] = set()

    for page in source_pages():
        target = target_for(page)
        expected_targets.add(target)
        content = build_export(page)

        if target.exists() and not is_generated(target):
            problems.append(
                f"Refusing to overwrite hand-authored rule file: {target.relative_to(ROOT)}"
            )
            continue

        if check:
            if not target.exists():
                problems.append(f"Missing rule export: {target.relative_to(ROOT)}")
            elif read_text(target) != content:
                problems.append(f"Stale rule export: {target.relative_to(ROOT)}")
        else:
            if not target.exists() or read_text(target) != content:
                target.write_text(content, encoding="utf-8")
                print(f"wrote {target.relative_to(ROOT)}")

    for existing in sorted(OUTPUT_DIR.glob("*.mdc")):
        if existing in expected_targets:
            continue
        if is_generated(existing):
            if check:
                problems.append(
                    f"Stale generated rule export (source page removed): {existing.relative_to(ROOT)}"
                )
            else:
                existing.unlink()
                print(f"removed {existing.relative_to(ROOT)}")

    if problems:
        for problem in problems:
            print(problem, file=sys.stderr)
        return 1

    if check:
        print("Rule exports are in sync.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify exports match the wiki pages without writing (exit non-zero on drift).",
    )
    args = parser.parse_args()
    return run(check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
